// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTSZkEFmB9tcY8fSZhN6-A7SEa53LNySw',
    appId: '1:276398452323:web:d9eb9b891d5c1e34875256',
    messagingSenderId: '276398452323',
    projectId: 'petpal-d6248',
    authDomain: 'petpal-d6248.firebaseapp.com',
    storageBucket: 'petpal-d6248.appspot.com',
    measurementId: 'G-XCRF4LEP7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkblaxJZFUdd2rsUm-V35nMsUFMOVu9ow',
    appId: '1:276398452323:android:80a36a9f82adcc3b875256',
    messagingSenderId: '276398452323',
    projectId: 'petpal-d6248',
    storageBucket: 'petpal-d6248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQtTqNZho7hIKiIS824vozxPL00NMA-s',
    appId: '1:276398452323:ios:d0c064759296ef22875256',
    messagingSenderId: '276398452323',
    projectId: 'petpal-d6248',
    storageBucket: 'petpal-d6248.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQtTqNZho7hIKiIS824vozxPL00NMA-s',
    appId: '1:276398452323:ios:434e203517d3195b875256',
    messagingSenderId: '276398452323',
    projectId: 'petpal-d6248',
    storageBucket: 'petpal-d6248.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
